#cross validation : 
instead of spiltting the training adn testing data into once,we can spilt the data into multiple train-test-spilts 


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris

# Load dataset
X, y = load_iris(return_X_y=True)

# Split data (holdout method)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train model

model = LogisticRegression(max_iter=200)
model.fit(X_train, y_train)

# Evaluate
y_pred = model.predict(X_test)
print("Accuracy (Holdout):", accuracy_score(y_test, y_pred))


Accuracy (Holdout): 1.0


Kfold is spilt the dataset into the k parts. in each iteration of k it takes 4 parts for training and 1 for testing  

In [ ]:
# pre requsties
from sklearn.model_selection import KFold, cross_val_score

# 
kfold=KFold(n_splits=5,shuffle=True,random_state=42)
model=LogisticRegression(max_iter=100) # model creation 
scores=cross_val_score(model,X,y,cv=kfold)
print('kfold accuracy ',scores)
print('mean accuracy ',  scores.mean()) # accuracy 


kfold scores  [1.         1.         0.93333333 0.96666667 0.96666667]
mean accuracy  0.9733333333333334


Stratified Kfold : is same as kfold but little variation. the dataset is divide into n splits.where class is a each part. for training it take equal amount of data from each class 

In [ ]:
from sklearn.model_selection import StratifiedKFold, cross_val_score

skf=StratifiedKFold(n_splits=5,shuffle=True, random_state=42)
scores=cross_val_score(model,X,y,cv=skf)

print('stratified kfold accuracy',scores)
print(scores.mean)

Leave one out : it leave 1 for testing remaining all samples for training these repeat upto based on n_spilts 

In [11]:
from sklearn.model_selection import LeaveOneOut, cross_val_score
loo=LeaveOneOut()
scores=cross_val_score(model,X,y,cv=loo)

print('LeaveOneOut accuracy',scores)
print('mean accuracy',scores.mean())

c:\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_resu

LeaveOneOut accuracy [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1.
 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1.]
mean accuracy 0.9666666666666667


In [ ]:
from sklearn.model_selection import LeavePOut, cross_val_score

lpo=LeavePOut(p=2)
scores=cross_val_score(model,X,y,cv=lpo)

print('leavepout accuracies',scores)
print('mean of accuracy:', scores.mean())

regresssion metrics 

In [ ]:
import numpy as np 
from sklearn.metrics import mean_absolute_error,mean_squared_error, r2_score

# example 
y_true = np.array([3, -0.5, 2, 7])
y_pred = np.array([2.5, 0.0, 2, 8])

mae=mean_absolute_error(y_true,y_pred)

# mse
mse=mean_absolute_error(y_true,y_pred)

# rmse
rmse=np.sqrt(mse)

# r2
r2=r2_score(y_true,y_pred)

print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R² Score:", r2)


classification parameters 

In [13]:
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score,confusion_matrix

y_true = [1, 0, 1, 1, 0, 1, 0, 0, 1, 0]  # Actual
y_pred = [1, 0, 1, 0, 0, 1, 1, 0, 1, 0]  # Predicted

acc = accuracy_score(y_true, y_pred)
prec = precision_score(y_true, y_pred)
rec = recall_score(y_true, y_pred)
f1 = f1_score(y_true, y_pred)
cm = confusion_matrix(y_true, y_pred)


print("Confusion Matrix:\n", cm)
print("Accuracy:", acc)
print("Precision:", prec)
print("Recall:", rec)
print("F1-Score:", f1)


Confusion Matrix:
 [[4 1]
 [1 4]]
Accuracy: 0.8
Precision: 0.8
Recall: 0.8
F1-Score: 0.8


Feature engineering : Normalization

In [15]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np 

data=np.array([[10],[20],[30],[40],[50]])
scalar=MinMaxScaler()
normalized=scalar.fit_transform(data)
print(normalized.flatten())

[0.   0.25 0.5  0.75 1.  ]


Standardization

In [16]:
from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()

standardized=scalar.fit_transform(data)
print(standardized.flatten())


[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


Label Encoder 

In [18]:
from sklearn.preprocessing import OneHotEncoder
colors=np.array([['red'],['blue'],['green'],['blue']])
encoder=OneHotEncoder()
one_hot=encoder.fit_transform(colors)
print(one_hot)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4 stored elements and shape (4, 3)>
  Coords	Values
  (0, 2)	1.0
  (1, 0)	1.0
  (2, 1)	1.0
  (3, 0)	1.0


In [19]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
labels = encoder.fit_transform(["Red", "Blue", "Green", "Blue"])
print(labels)  # [2 0 1 0]


[2 0 1 0]
